added pr template
luckykumarirai/easy-education pull request #16
Opened 2021-02-14 08:18 UTC by Sloth-Panda

corresponds to issue -> #1

2021-02-14 10:32 UTC, luckykumarirai requested changes
Remove these parts it makes too lengthy, make it simple.
add 2 or 3 checklists only

> which parts @luckykumarirai

<!--
Example how to mark a checkbox:-
- [x] My code follows the code style of this project.
-->
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. 

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
A clear and concise description of it.

## Checklist:
<!--
Example how to mark a checkbox:-
- [x] My code follows the code style of this project.
-->
- [ ] My code follows the style guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] New and existing unit tests pass locally with my changes.

2021-02-14 10:34 UTC, Sloth-Panda commented
which parts @luckykumarirai

2021-02-14 10:41 UTC, luckykumarirai commented on .github/pull_request_template.md
> +- [ ] My code follows the style guidelines of this project.
Add this checklist.

2021-02-14 10:41 UTC, luckykumarirai commented on .github/pull_request_template.md
> +- [ ] I have made corresponding changes to the documentation.
Add these 3 also.

2021-02-15 11:34 UTC, luckykumarirai commented
Can you work on this ASAP @Sloth-Panda? I need a proper template to make it easy for me to review PRs.

2021-02-15 12:18 UTC, Sloth-Panda commented
@luckykumarirai check it now

2021-02-15 17:10 UTC, merged

2021-02-15 17:11 UTC, luckykumarirai commented
Nice work!