removed-background-vidio
luckykumarirai/easy-education pull request #45
Opened 2021-02-26 05:08 UTC by raman-thakur

## Related Issue
  improve the home page design

Closes: #42 

#### Describe the changes you've made
I have added an image in the background and removed the video.

#### Describe if there is any unusual behavior of your code(Write `NA` if there isn't)
no unusual behavior 

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.

## Screenshots

 Original           | Updated
 :--------------------: |:--------------------:
 **original screenshot**  | <b>updated screenshot </b> |

2021-02-26 05:09 UTC, raman-thakur commented
@luckykumarirai  that image in the background is responsive and will fit in all screen sizes.

2021-02-28 06:58 UTC, luckykumarirai approved these changes

2021-02-28 06:59 UTC, luckykumarirai requested changes
Resolve conflicts

2021-03-09 12:06 UTC, luckykumarirai commented
@raman-thakur Resolve the conflict then i can only  merge.

2021-03-13 08:34 UTC, merged